# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ArmUi.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setWindowModality(QtCore.Qt.NonModal)
        Form.setEnabled(True)
        Form.resize(1200, 620)
        Form.setMinimumSize(QtCore.QSize(0, 0))
        Form.setMaximumSize(QtCore.QSize(1200, 620))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        Form.setFont(font)
        Form.setFocusPolicy(QtCore.Qt.NoFocus)
        Form.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        Form.setAcceptDrops(False)
        Form.setAutoFillBackground(False)
        Form.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setGeometry(QtCore.QRect(0, 10, 1200, 600))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_1 = QtWidgets.QWidget()
        self.tab_1.setObjectName("tab_1")
        self.widget_5 = QtWidgets.QWidget(self.tab_1)
        self.widget_5.setGeometry(QtCore.QRect(910, 360, 281, 211))
        self.widget_5.setStyleSheet("#widget_5 {border:1px solid #242424;\n"
"border-color: rgb(200, 200, 200);}")
        self.widget_5.setObjectName("widget_5")
        self.label_action = QtWidgets.QLabel(self.widget_5)
        self.label_action.setGeometry(QtCore.QRect(5, 20, 111, 30))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.label_action.setFont(font)
        self.label_action.setObjectName("label_action")
        self.comboBox_action = QtWidgets.QComboBox(self.widget_5)
        self.comboBox_action.setGeometry(QtCore.QRect(110, 18, 71, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.comboBox_action.setFont(font)
        self.comboBox_action.setStyleSheet("background-color: rgb(240, 240, 240);\n"
"")
        self.comboBox_action.setObjectName("comboBox_action")
        self.Button_DelectSingle = QtWidgets.QPushButton(self.widget_5)
        self.Button_DelectSingle.setGeometry(QtCore.QRect(10, 60, 140, 41))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.Button_DelectSingle.setFont(font)
        self.Button_DelectSingle.setStyleSheet("QPushButton{background-color: rgb(255, 165, 0);}\n"
"QPushButton:hover{background-color:  rgb(255, 210, 0);}\n"
"QPushButton{border-radius:5px;}")
        self.Button_DelectSingle.setObjectName("Button_DelectSingle")
        self.Button_AllDelect = QtWidgets.QPushButton(self.widget_5)
        self.Button_AllDelect.setGeometry(QtCore.QRect(160, 60, 110, 41))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.Button_AllDelect.setFont(font)
        self.Button_AllDelect.setStyleSheet("QPushButton{background-color: rgb(255, 165, 0);}\n"
"QPushButton:hover{background-color:  rgb(255, 210, 0);}\n"
"QPushButton{border-radius:5px;}")
        self.Button_AllDelect.setObjectName("Button_AllDelect")
        self.Button_RunAction = QtWidgets.QPushButton(self.widget_5)
        self.Button_RunAction.setGeometry(QtCore.QRect(10, 110, 140, 41))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.Button_RunAction.setFont(font)
        self.Button_RunAction.setStyleSheet("QPushButton{background-color: rgb(255, 165, 0);}\n"
"QPushButton:hover{background-color:  rgb(255, 210, 0);}\n"
"QPushButton{border-radius:5px;}")
        self.Button_RunAction.setObjectName("Button_RunAction")
        self.Button_StopAction = QtWidgets.QPushButton(self.widget_5)
        self.Button_StopAction.setGeometry(QtCore.QRect(160, 110, 110, 41))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.Button_StopAction.setFont(font)
        self.Button_StopAction.setStyleSheet("QPushButton{background-color: rgb(255, 165, 0);}\n"
"QPushButton:hover{background-color:  rgb(255, 210, 0);}\n"
"QPushButton{border-radius:5px;}")
        self.Button_StopAction.setObjectName("Button_StopAction")
        self.Button_Quit = QtWidgets.QPushButton(self.widget_5)
        self.Button_Quit.setGeometry(QtCore.QRect(100, 160, 100, 41))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.Button_Quit.setFont(font)
        self.Button_Quit.setStyleSheet("QPushButton{background-color: rgb(255, 165, 0);}\n"
"QPushButton:hover{background-color:  rgb(255, 210, 0);}\n"
"QPushButton{border-radius:5px;}")
        self.Button_Quit.setObjectName("Button_Quit")
        self.Button_Reflash = QtWidgets.QPushButton(self.widget_5)
        self.Button_Reflash.setGeometry(QtCore.QRect(200, 12, 71, 41))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.Button_Reflash.setFont(font)
        self.Button_Reflash.setStyleSheet("QPushButton{background-color: rgb(255, 165, 0);}\n"
"QPushButton:hover{background-color:  rgb(255, 210, 0);}\n"
"QPushButton{border-radius:5px;}")
        self.Button_Reflash.setObjectName("Button_Reflash")
        self.widget_3 = QtWidgets.QWidget(self.tab_1)
        self.widget_3.setGeometry(QtCore.QRect(670, 360, 90, 211))
        self.widget_3.setStyleSheet("#widget_3 {border:1px solid #242424;\n"
"border-color: rgb(200, 200, 200);}")
        self.widget_3.setObjectName("widget_3")
        self.checkBox = QtWidgets.QCheckBox(self.widget_3)
        self.checkBox.setGeometry(QtCore.QRect(12, 40, 68, 40))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.checkBox.setFont(font)
        self.checkBox.setObjectName("checkBox")
        self.Button_Run = QtWidgets.QPushButton(self.widget_3)
        self.Button_Run.setGeometry(QtCore.QRect(10, 100, 70, 81))
        font = QtGui.QFont()
        font.setFamily("SimHei")
        font.setPointSize(20)
        self.Button_Run.setFont(font)
        self.Button_Run.setStyleSheet("QPushButton{background-color: rgb(255, 165, 0);}\n"
"QPushButton:hover{background-color:  rgb(255, 210, 0);}\n"
"QPushButton{border-radius:5px;}")
        self.Button_Run.setIconSize(QtCore.QSize(14, 14))
        self.Button_Run.setObjectName("Button_Run")
        self.widget_2 = QtWidgets.QWidget(self.tab_1)
        self.widget_2.setGeometry(QtCore.QRect(485, 360, 181, 211))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.widget_2.setFont(font)
        self.widget_2.setStyleSheet("#widget_2 {border:1px solid #242424;\n"
"border-color: rgb(200, 200, 200);}")
        self.widget_2.setObjectName("widget_2")
        self.Button_ReadDeviation = QtWidgets.QPushButton(self.widget_2)
        self.Button_ReadDeviation.setGeometry(QtCore.QRect(10, 15, 160, 51))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.Button_ReadDeviation.setFont(font)
        self.Button_ReadDeviation.setStyleSheet("QPushButton{background-color: rgb(255, 165, 0);}\n"
"QPushButton:hover{background-color:  rgb(255, 210, 0);}\n"
"QPushButton{border-radius:5px;}")
        self.Button_ReadDeviation.setObjectName("Button_ReadDeviation")
        self.Button_SaveDeviation = QtWidgets.QPushButton(self.widget_2)
        self.Button_SaveDeviation.setGeometry(QtCore.QRect(10, 80, 160, 51))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.Button_SaveDeviation.setFont(font)
        self.Button_SaveDeviation.setStyleSheet("QPushButton{background-color: rgb(255, 165, 0);}\n"
"QPushButton:hover{background-color:  rgb(255, 210, 0);}\n"
"QPushButton{border-radius:5px;}")
        self.Button_SaveDeviation.setObjectName("Button_SaveDeviation")
        self.Button_ReSetServos = QtWidgets.QPushButton(self.widget_2)
        self.Button_ReSetServos.setGeometry(QtCore.QRect(10, 140, 160, 51))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.Button_ReSetServos.setFont(font)
        self.Button_ReSetServos.setStyleSheet("QPushButton{background-color: rgb(255, 165, 0);}\n"
"QPushButton:hover{background-color:  rgb(255, 210, 0);}\n"
"QPushButton{border-radius:5px;}")
        self.Button_ReSetServos.setObjectName("Button_ReSetServos")
        self.tableWidget = QtWidgets.QTableWidget(self.tab_1)
        self.tableWidget.setGeometry(QtCore.QRect(485, 0, 711, 231))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget.sizePolicy().hasHeightForWidth())
        self.tableWidget.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(11)
        self.tableWidget.setFont(font)
        self.tableWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tableWidget.setStyleSheet("border:1px solid #242424;\n"
"border-color: rgb(200, 200, 200);")
        self.tableWidget.setTextElideMode(QtCore.Qt.ElideMiddle)
        self.tableWidget.setRowCount(0)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(8)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(11)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignTop)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignTop)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignTop)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignTop)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignTop)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignTop)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignTop)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(7, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(88)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(20)
        self.tableWidget.horizontalHeader().setSortIndicatorShown(True)
        self.tableWidget.verticalHeader().setVisible(False)
        self.tableWidget.verticalHeader().setDefaultSectionSize(22)
        self.tableWidget.verticalHeader().setMinimumSectionSize(22)
        self.widget_4 = QtWidgets.QWidget(self.tab_1)
        self.widget_4.setGeometry(QtCore.QRect(765, 360, 141, 211))
        self.widget_4.setStyleSheet("#widget_4 {border:1px solid #242424;\n"
"border-color: rgb(200, 200, 200);}")
        self.widget_4.setObjectName("widget_4")
        self.Button_OpenActionGroup = QtWidgets.QPushButton(self.widget_4)
        self.Button_OpenActionGroup.setGeometry(QtCore.QRect(5, 15, 130, 51))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.Button_OpenActionGroup.setFont(font)
        self.Button_OpenActionGroup.setStyleSheet("QPushButton{background-color: rgb(255, 165, 0);}\n"
"QPushButton:hover{background-color:  rgb(255, 210, 0);}\n"
"QPushButton{border-radius:5px;}")
        self.Button_OpenActionGroup.setObjectName("Button_OpenActionGroup")
        self.Button_SaveActionGroup = QtWidgets.QPushButton(self.widget_4)
        self.Button_SaveActionGroup.setGeometry(QtCore.QRect(5, 80, 130, 51))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.Button_SaveActionGroup.setFont(font)
        self.Button_SaveActionGroup.setStyleSheet("QPushButton{background-color: rgb(255, 165, 0);}\n"
"QPushButton:hover{background-color:  rgb(255, 210, 0);}\n"
"QPushButton{border-radius:5px;}")
        self.Button_SaveActionGroup.setObjectName("Button_SaveActionGroup")
        self.Button_TandemActionGroup = QtWidgets.QPushButton(self.widget_4)
        self.Button_TandemActionGroup.setGeometry(QtCore.QRect(5, 145, 130, 51))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.Button_TandemActionGroup.setFont(font)
        self.Button_TandemActionGroup.setStyleSheet("QPushButton{background-color: rgb(255, 165, 0);}\n"
"QPushButton:hover{background-color:  rgb(255, 210, 0);}\n"
"QPushButton{border-radius:5px;}")
        self.Button_TandemActionGroup.setObjectName("Button_TandemActionGroup")
        self.widget_1 = QtWidgets.QWidget(self.tab_1)
        self.widget_1.setGeometry(QtCore.QRect(485, 240, 711, 111))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.widget_1.setFont(font)
        self.widget_1.setStyleSheet("#widget_1 {border:1px solid #242424;\n"
"border-color: rgb(200, 200, 200);}")
        self.widget_1.setObjectName("widget_1")
        self.label_time = QtWidgets.QLabel(self.widget_1)
        self.label_time.setGeometry(QtCore.QRect(20, 20, 111, 31))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.label_time.setFont(font)
        self.label_time.setObjectName("label_time")
        self.lineEdit_time = QtWidgets.QLineEdit(self.widget_1)
        self.lineEdit_time.setGeometry(QtCore.QRect(140, 20, 41, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.lineEdit_time.setFont(font)
        self.lineEdit_time.setMaxLength(30000)
        self.lineEdit_time.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_time.setObjectName("lineEdit_time")
        self.Button_AddAction = QtWidgets.QPushButton(self.widget_1)
        self.Button_AddAction.setGeometry(QtCore.QRect(225, 26, 110, 60))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.Button_AddAction.setFont(font)
        self.Button_AddAction.setStyleSheet("QPushButton{background-color: rgb(255, 165, 0);}\n"
"QPushButton:hover{background-color:  rgb(255, 210, 0);}\n"
"QPushButton{border-radius:5px;}")
        self.Button_AddAction.setObjectName("Button_AddAction")
        self.Button_DelectAction = QtWidgets.QPushButton(self.widget_1)
        self.Button_DelectAction.setGeometry(QtCore.QRect(350, 10, 110, 41))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.Button_DelectAction.setFont(font)
        self.Button_DelectAction.setStyleSheet("QPushButton{background-color: rgb(255, 165, 0);}\n"
"QPushButton:hover{background-color:  rgb(255, 210, 0);}\n"
"QPushButton{border-radius:5px;}")
        self.Button_DelectAction.setObjectName("Button_DelectAction")
        self.Button_UpdateAction = QtWidgets.QPushButton(self.widget_1)
        self.Button_UpdateAction.setGeometry(QtCore.QRect(470, 10, 110, 41))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.Button_UpdateAction.setFont(font)
        self.Button_UpdateAction.setStyleSheet("QPushButton{background-color: rgb(255, 165, 0);}\n"
"QPushButton:hover{background-color:  rgb(255, 210, 0);}\n"
"QPushButton{border-radius:5px;}")
        self.Button_UpdateAction.setObjectName("Button_UpdateAction")
        self.Button_InsertAction = QtWidgets.QPushButton(self.widget_1)
        self.Button_InsertAction.setGeometry(QtCore.QRect(470, 60, 110, 41))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.Button_InsertAction.setFont(font)
        self.Button_InsertAction.setStyleSheet("QPushButton{background-color: rgb(255, 165, 0);}\n"
"QPushButton:hover{background-color:  rgb(255, 210, 0);}\n"
"QPushButton{border-radius:5px;}")
        self.Button_InsertAction.setObjectName("Button_InsertAction")
        self.Button_MoveUpAction = QtWidgets.QPushButton(self.widget_1)
        self.Button_MoveUpAction.setGeometry(QtCore.QRect(590, 10, 110, 41))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.Button_MoveUpAction.setFont(font)
        self.Button_MoveUpAction.setStyleSheet("QPushButton{background-color: rgb(255, 165, 0);}\n"
"QPushButton:hover{background-color:  rgb(255, 210, 0);}\n"
"QPushButton{border-radius:5px;}")
        self.Button_MoveUpAction.setObjectName("Button_MoveUpAction")
        self.Button_MoveDownAction = QtWidgets.QPushButton(self.widget_1)
        self.Button_MoveDownAction.setGeometry(QtCore.QRect(590, 60, 110, 41))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.Button_MoveDownAction.setFont(font)
        self.Button_MoveDownAction.setStyleSheet("QPushButton{background-color: rgb(255, 165, 0);}\n"
"QPushButton:hover{background-color:  rgb(255, 210, 0);}\n"
"QPushButton{border-radius:5px;}")
        self.Button_MoveDownAction.setObjectName("Button_MoveDownAction")
        self.label_time_2 = QtWidgets.QLabel(self.widget_1)
        self.label_time_2.setGeometry(QtCore.QRect(20, 60, 91, 31))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.label_time_2.setFont(font)
        self.label_time_2.setObjectName("label_time_2")
        self.label = QtWidgets.QLabel(self.widget_1)
        self.label.setGeometry(QtCore.QRect(190, 25, 16, 21))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(8)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_5 = QtWidgets.QLabel(self.widget_1)
        self.label_5.setGeometry(QtCore.QRect(190, 65, 16, 21))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.label_TotalTime = QtWidgets.QLabel(self.widget_1)
        self.label_TotalTime.setGeometry(QtCore.QRect(130, 65, 60, 20))
        self.label_TotalTime.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_TotalTime.setAlignment(QtCore.Qt.AlignCenter)
        self.label_TotalTime.setObjectName("label_TotalTime")
        self.Button_DelectAllAction = QtWidgets.QPushButton(self.widget_1)
        self.Button_DelectAllAction.setGeometry(QtCore.QRect(350, 60, 110, 41))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.Button_DelectAllAction.setFont(font)
        self.Button_DelectAllAction.setStyleSheet("QPushButton{background-color: rgb(255, 165, 0);}\n"
"QPushButton:hover{background-color:  rgb(255, 210, 0);}\n"
"QPushButton{border-radius:5px;}")
        self.Button_DelectAllAction.setObjectName("Button_DelectAllAction")
        self.frame = QtWidgets.QFrame(self.tab_1)
        self.frame.setGeometry(QtCore.QRect(-15, -5, 498, 571))
        self.frame.setStyleSheet("background-image: url(:/images/Arm.png)")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.radioButton_zn = QtWidgets.QRadioButton(self.frame)
        self.radioButton_zn.setGeometry(QtCore.QRect(20, 10, 61, 27))
        self.radioButton_zn.setObjectName("radioButton_zn")
        self.radioButton_en = QtWidgets.QRadioButton(self.frame)
        self.radioButton_en.setGeometry(QtCore.QRect(100, 10, 81, 27))
        self.radioButton_en.setObjectName("radioButton_en")
        self.widget_id1 = QtWidgets.QWidget(self.frame)
        self.widget_id1.setGeometry(QtCore.QRect(130, 130, 121, 110))
        self.widget_id1.setStyleSheet("background-color: rgb(255, 176, 97, 200);\n"
"border-radius:10px;")
        self.widget_id1.setObjectName("widget_id1")
        self.label_ID1 = QtWidgets.QLabel(self.widget_id1)
        self.label_ID1.setGeometry(QtCore.QRect(45, 0, 32, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.label_ID1.setFont(font)
        self.label_ID1.setStyleSheet("background-color: rgb(255, 255, 255， 0);\n"
"border-radius:0px;")
        self.label_ID1.setObjectName("label_ID1")
        self.horizontalSlider_1 = QtWidgets.QSlider(self.widget_id1)
        self.horizontalSlider_1.setGeometry(QtCore.QRect(10, 20, 100, 22))
        self.horizontalSlider_1.setAutoFillBackground(False)
        self.horizontalSlider_1.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"border-radius:0px;")
        self.horizontalSlider_1.setMinimum(500)
        self.horizontalSlider_1.setMaximum(2500)
        self.horizontalSlider_1.setPageStep(1)
        self.horizontalSlider_1.setProperty("value", 1500)
        self.horizontalSlider_1.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_1.setObjectName("horizontalSlider_1")
        self.lineEdit_1 = QtWidgets.QLineEdit(self.widget_id1)
        self.lineEdit_1.setGeometry(QtCore.QRect(40, 50, 38, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_1.sizePolicy().hasHeightForWidth())
        self.lineEdit_1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.lineEdit_1.setFont(font)
        self.lineEdit_1.setAutoFillBackground(False)
        self.lineEdit_1.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:0px;")
        self.lineEdit_1.setMaxLength(1000)
        self.lineEdit_1.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_1.setDragEnabled(False)
        self.lineEdit_1.setReadOnly(False)
        self.lineEdit_1.setObjectName("lineEdit_1")
        self.horizontalSlider_11 = QtWidgets.QSlider(self.widget_id1)
        self.horizontalSlider_11.setGeometry(QtCore.QRect(35, 85, 50, 20))
        self.horizontalSlider_11.setStyleSheet("background-color: rgb(255, 255, 255， 0);")
        self.horizontalSlider_11.setMinimum(-150)
        self.horizontalSlider_11.setMaximum(150)
        self.horizontalSlider_11.setPageStep(1)
        self.horizontalSlider_11.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_11.setObjectName("horizontalSlider_11")
        self.label_d1 = QtWidgets.QLabel(self.widget_id1)
        self.label_d1.setGeometry(QtCore.QRect(5, 87, 31, 16))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(10)
        self.label_d1.setFont(font)
        self.label_d1.setStyleSheet("background-color: rgb(255, 255, 255， 0);")
        self.label_d1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_d1.setObjectName("label_d1")
        self.label_2 = QtWidgets.QLabel(self.widget_id1)
        self.label_2.setGeometry(QtCore.QRect(3, 55, 40, 21))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background-color: rgb(255, 255, 255， 0);")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.widget_id1)
        self.label_3.setGeometry(QtCore.QRect(82, 55, 40, 21))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("background-color: rgb(255, 255, 255， 0);")
        self.label_3.setObjectName("label_3")
        self.widget_id3 = QtWidgets.QWidget(self.frame)
        self.widget_id3.setGeometry(QtCore.QRect(270, 50, 120, 110))
        self.widget_id3.setStyleSheet("background-color: rgb(255, 176, 97, 200);\n"
"border-radius:10px;")
        self.widget_id3.setObjectName("widget_id3")
        self.label_ID3 = QtWidgets.QLabel(self.widget_id3)
        self.label_ID3.setGeometry(QtCore.QRect(45, 0, 32, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.label_ID3.setFont(font)
        self.label_ID3.setStyleSheet("background-color: rgb(255, 255, 255， 0);\n"
"border-radius:0px;")
        self.label_ID3.setObjectName("label_ID3")
        self.horizontalSlider_3 = QtWidgets.QSlider(self.widget_id3)
        self.horizontalSlider_3.setGeometry(QtCore.QRect(10, 20, 100, 22))
        self.horizontalSlider_3.setAutoFillBackground(False)
        self.horizontalSlider_3.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"border-radius:0px;")
        self.horizontalSlider_3.setMinimum(500)
        self.horizontalSlider_3.setMaximum(2500)
        self.horizontalSlider_3.setPageStep(1)
        self.horizontalSlider_3.setProperty("value", 1500)
        self.horizontalSlider_3.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_3.setObjectName("horizontalSlider_3")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.widget_id3)
        self.lineEdit_3.setGeometry(QtCore.QRect(40, 50, 41, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setAutoFillBackground(False)
        self.lineEdit_3.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:0px;")
        self.lineEdit_3.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_3.setReadOnly(False)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_7 = QtWidgets.QLabel(self.widget_id3)
        self.label_7.setGeometry(QtCore.QRect(82, 55, 40, 21))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("background-color: rgb(255, 255, 255， 0);")
        self.label_7.setObjectName("label_7")
        self.label_d3 = QtWidgets.QLabel(self.widget_id3)
        self.label_d3.setGeometry(QtCore.QRect(5, 87, 31, 16))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(10)
        self.label_d3.setFont(font)
        self.label_d3.setStyleSheet("background-color: rgb(255, 255, 255， 0);")
        self.label_d3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_d3.setObjectName("label_d3")
        self.label_9 = QtWidgets.QLabel(self.widget_id3)
        self.label_9.setGeometry(QtCore.QRect(2, 55, 40, 21))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("background-color: rgb(255, 255, 255， 0);")
        self.label_9.setObjectName("label_9")
        self.horizontalSlider_13 = QtWidgets.QSlider(self.widget_id3)
        self.horizontalSlider_13.setGeometry(QtCore.QRect(35, 85, 50, 20))
        self.horizontalSlider_13.setStyleSheet("background-color: rgb(255, 255, 255， 0);")
        self.horizontalSlider_13.setMinimum(-150)
        self.horizontalSlider_13.setMaximum(150)
        self.horizontalSlider_13.setPageStep(1)
        self.horizontalSlider_13.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_13.setObjectName("horizontalSlider_13")
        self.widget_id4 = QtWidgets.QWidget(self.frame)
        self.widget_id4.setGeometry(QtCore.QRect(370, 170, 120, 110))
        self.widget_id4.setStyleSheet("background-color: rgb(255, 176, 97, 200);\n"
"border-radius:10px;")
        self.widget_id4.setObjectName("widget_id4")
        self.horizontalSlider_4 = QtWidgets.QSlider(self.widget_id4)
        self.horizontalSlider_4.setGeometry(QtCore.QRect(10, 20, 100, 22))
        self.horizontalSlider_4.setAutoFillBackground(False)
        self.horizontalSlider_4.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"border-radius:0px;")
        self.horizontalSlider_4.setMinimum(500)
        self.horizontalSlider_4.setMaximum(2500)
        self.horizontalSlider_4.setPageStep(1)
        self.horizontalSlider_4.setProperty("value", 1500)
        self.horizontalSlider_4.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_4.setObjectName("horizontalSlider_4")
        self.label_ID4 = QtWidgets.QLabel(self.widget_id4)
        self.label_ID4.setGeometry(QtCore.QRect(45, 0, 32, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.label_ID4.setFont(font)
        self.label_ID4.setStyleSheet("background-color: rgb(255, 255, 255， 0);\n"
"border-radius:0px;")
        self.label_ID4.setObjectName("label_ID4")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.widget_id4)
        self.lineEdit_4.setGeometry(QtCore.QRect(40, 50, 41, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.lineEdit_4.setFont(font)
        self.lineEdit_4.setAutoFillBackground(False)
        self.lineEdit_4.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:0px;")
        self.lineEdit_4.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_4.setReadOnly(False)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label_10 = QtWidgets.QLabel(self.widget_id4)
        self.label_10.setGeometry(QtCore.QRect(82, 50, 40, 21))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("background-color: rgb(255, 255, 255， 0);")
        self.label_10.setObjectName("label_10")
        self.label_d4 = QtWidgets.QLabel(self.widget_id4)
        self.label_d4.setGeometry(QtCore.QRect(5, 87, 31, 16))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(10)
        self.label_d4.setFont(font)
        self.label_d4.setStyleSheet("background-color: rgb(255, 255, 255， 0);")
        self.label_d4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_d4.setObjectName("label_d4")
        self.label_12 = QtWidgets.QLabel(self.widget_id4)
        self.label_12.setGeometry(QtCore.QRect(2, 50, 40, 21))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("background-color: rgb(255, 255, 255， 0);")
        self.label_12.setObjectName("label_12")
        self.horizontalSlider_14 = QtWidgets.QSlider(self.widget_id4)
        self.horizontalSlider_14.setGeometry(QtCore.QRect(35, 85, 50, 20))
        self.horizontalSlider_14.setStyleSheet("background-color: rgb(255, 255, 255， 0);")
        self.horizontalSlider_14.setMinimum(-150)
        self.horizontalSlider_14.setMaximum(150)
        self.horizontalSlider_14.setPageStep(1)
        self.horizontalSlider_14.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_14.setObjectName("horizontalSlider_14")
        self.widget_id5 = QtWidgets.QWidget(self.frame)
        self.widget_id5.setGeometry(QtCore.QRect(250, 280, 120, 110))
        self.widget_id5.setStyleSheet("background-color: rgb(255, 176, 97, 200);\n"
"border-radius:10px;")
        self.widget_id5.setObjectName("widget_id5")
        self.horizontalSlider_5 = QtWidgets.QSlider(self.widget_id5)
        self.horizontalSlider_5.setGeometry(QtCore.QRect(10, 20, 100, 22))
        self.horizontalSlider_5.setAutoFillBackground(False)
        self.horizontalSlider_5.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"border-radius:0px;")
        self.horizontalSlider_5.setMinimum(500)
        self.horizontalSlider_5.setMaximum(2500)
        self.horizontalSlider_5.setPageStep(1)
        self.horizontalSlider_5.setProperty("value", 1500)
        self.horizontalSlider_5.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_5.setObjectName("horizontalSlider_5")
        self.label_ID5 = QtWidgets.QLabel(self.widget_id5)
        self.label_ID5.setGeometry(QtCore.QRect(45, 0, 32, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.label_ID5.setFont(font)
        self.label_ID5.setStyleSheet("background-color: rgb(255, 255, 255， 0);\n"
"border-radius:0px;")
        self.label_ID5.setObjectName("label_ID5")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.widget_id5)
        self.lineEdit_5.setGeometry(QtCore.QRect(40, 50, 41, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.lineEdit_5.setFont(font)
        self.lineEdit_5.setAutoFillBackground(False)
        self.lineEdit_5.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:0px;")
        self.lineEdit_5.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_5.setReadOnly(False)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.label_13 = QtWidgets.QLabel(self.widget_id5)
        self.label_13.setGeometry(QtCore.QRect(82, 50, 40, 21))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("background-color: rgb(255, 255, 255， 0);")
        self.label_13.setObjectName("label_13")
        self.label_d5 = QtWidgets.QLabel(self.widget_id5)
        self.label_d5.setGeometry(QtCore.QRect(5, 87, 31, 16))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(10)
        self.label_d5.setFont(font)
        self.label_d5.setStyleSheet("background-color: rgb(255, 255, 255， 0);")
        self.label_d5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_d5.setObjectName("label_d5")
        self.label_15 = QtWidgets.QLabel(self.widget_id5)
        self.label_15.setGeometry(QtCore.QRect(2, 50, 40, 21))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.label_15.setFont(font)
        self.label_15.setStyleSheet("background-color: rgb(255, 255, 255， 0);")
        self.label_15.setObjectName("label_15")
        self.horizontalSlider_15 = QtWidgets.QSlider(self.widget_id5)
        self.horizontalSlider_15.setGeometry(QtCore.QRect(35, 85, 50, 20))
        self.horizontalSlider_15.setStyleSheet("background-color: rgb(255, 255, 255， 0);")
        self.horizontalSlider_15.setMinimum(-150)
        self.horizontalSlider_15.setMaximum(150)
        self.horizontalSlider_15.setPageStep(1)
        self.horizontalSlider_15.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_15.setObjectName("horizontalSlider_15")
        self.widget_id6 = QtWidgets.QWidget(self.frame)
        self.widget_id6.setGeometry(QtCore.QRect(280, 420, 120, 110))
        self.widget_id6.setStyleSheet("background-color: rgb(255, 176, 97, 200);\n"
"border-radius:10px;")
        self.widget_id6.setObjectName("widget_id6")
        self.label_ID6 = QtWidgets.QLabel(self.widget_id6)
        self.label_ID6.setGeometry(QtCore.QRect(45, 0, 32, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.label_ID6.setFont(font)
        self.label_ID6.setStyleSheet("background-color: rgb(255, 255, 255， 0);\n"
"border-radius:0px;")
        self.label_ID6.setObjectName("label_ID6")
        self.horizontalSlider_6 = QtWidgets.QSlider(self.widget_id6)
        self.horizontalSlider_6.setGeometry(QtCore.QRect(10, 20, 100, 22))
        self.horizontalSlider_6.setAutoFillBackground(False)
        self.horizontalSlider_6.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"border-radius:0px;")
        self.horizontalSlider_6.setMinimum(500)
        self.horizontalSlider_6.setMaximum(2500)
        self.horizontalSlider_6.setPageStep(1)
        self.horizontalSlider_6.setProperty("value", 1500)
        self.horizontalSlider_6.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_6.setObjectName("horizontalSlider_6")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.widget_id6)
        self.lineEdit_6.setGeometry(QtCore.QRect(40, 50, 41, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.lineEdit_6.setFont(font)
        self.lineEdit_6.setAutoFillBackground(False)
        self.lineEdit_6.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:0px;")
        self.lineEdit_6.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_6.setReadOnly(False)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.label_16 = QtWidgets.QLabel(self.widget_id6)
        self.label_16.setGeometry(QtCore.QRect(82, 50, 40, 21))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.label_16.setFont(font)
        self.label_16.setStyleSheet("background-color: rgb(255, 255, 255， 0);")
        self.label_16.setObjectName("label_16")
        self.label_d6 = QtWidgets.QLabel(self.widget_id6)
        self.label_d6.setGeometry(QtCore.QRect(5, 87, 31, 16))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(10)
        self.label_d6.setFont(font)
        self.label_d6.setStyleSheet("background-color: rgb(255, 255, 255， 0);")
        self.label_d6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_d6.setObjectName("label_d6")
        self.label_18 = QtWidgets.QLabel(self.widget_id6)
        self.label_18.setGeometry(QtCore.QRect(2, 50, 40, 21))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.label_18.setFont(font)
        self.label_18.setStyleSheet("background-color: rgb(255, 255, 255， 0);")
        self.label_18.setObjectName("label_18")
        self.horizontalSlider_16 = QtWidgets.QSlider(self.widget_id6)
        self.horizontalSlider_16.setGeometry(QtCore.QRect(35, 85, 50, 20))
        self.horizontalSlider_16.setStyleSheet("background-color: rgb(255, 255, 255， 0);")
        self.horizontalSlider_16.setMinimum(-150)
        self.horizontalSlider_16.setMaximum(150)
        self.horizontalSlider_16.setPageStep(1)
        self.horizontalSlider_16.setProperty("value", 0)
        self.horizontalSlider_16.setSliderPosition(0)
        self.horizontalSlider_16.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_16.setObjectName("horizontalSlider_16")
        self.frame.raise_()
        self.widget_5.raise_()
        self.widget_3.raise_()
        self.widget_2.raise_()
        self.tableWidget.raise_()
        self.widget_4.raise_()
        self.widget_1.raise_()
        self.tabWidget.addTab(self.tab_1, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.label_8 = QtWidgets.QLabel(self.tab)
        self.label_8.setGeometry(QtCore.QRect(840, 10, 161, 31))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(16)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.widget_12 = QtWidgets.QWidget(self.tab)
        self.widget_12.setGeometry(QtCore.QRect(310, 380, 385, 161))
        self.widget_12.setStyleSheet("#widget_12 {border:1px solid #242424;\n"
"border-color: rgb(200, 200, 200);}")
        self.widget_12.setObjectName("widget_12")
        self.label_25 = QtWidgets.QLabel(self.widget_12)
        self.label_25.setGeometry(QtCore.QRect(5, 30, 15, 31))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        self.label_25.setFont(font)
        self.label_25.setAlignment(QtCore.Qt.AlignCenter)
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(self.widget_12)
        self.label_26.setGeometry(QtCore.QRect(5, 80, 15, 31))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        self.label_26.setFont(font)
        self.label_26.setAlignment(QtCore.Qt.AlignCenter)
        self.label_26.setObjectName("label_26")
        self.label_27 = QtWidgets.QLabel(self.widget_12)
        self.label_27.setGeometry(QtCore.QRect(5, 133, 15, 21))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        self.label_27.setFont(font)
        self.label_27.setAlignment(QtCore.Qt.AlignCenter)
        self.label_27.setObjectName("label_27")
        self.horizontalSlider_LMin = QtWidgets.QSlider(self.widget_12)
        self.horizontalSlider_LMin.setGeometry(QtCore.QRect(20, 35, 169, 22))
        self.horizontalSlider_LMin.setMaximum(255)
        self.horizontalSlider_LMin.setPageStep(1)
        self.horizontalSlider_LMin.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_LMin.setObjectName("horizontalSlider_LMin")
        self.horizontalSlider_AMin = QtWidgets.QSlider(self.widget_12)
        self.horizontalSlider_AMin.setGeometry(QtCore.QRect(20, 85, 169, 22))
        self.horizontalSlider_AMin.setMaximum(255)
        self.horizontalSlider_AMin.setPageStep(1)
        self.horizontalSlider_AMin.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_AMin.setObjectName("horizontalSlider_AMin")
        self.horizontalSlider_BMin = QtWidgets.QSlider(self.widget_12)
        self.horizontalSlider_BMin.setGeometry(QtCore.QRect(20, 135, 169, 22))
        self.horizontalSlider_BMin.setMaximum(255)
        self.horizontalSlider_BMin.setPageStep(1)
        self.horizontalSlider_BMin.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_BMin.setObjectName("horizontalSlider_BMin")
        self.label_LMin = QtWidgets.QLabel(self.widget_12)
        self.label_LMin.setGeometry(QtCore.QRect(80, 10, 51, 20))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        self.label_LMin.setFont(font)
        self.label_LMin.setAlignment(QtCore.Qt.AlignCenter)
        self.label_LMin.setObjectName("label_LMin")
        self.label_AMin = QtWidgets.QLabel(self.widget_12)
        self.label_AMin.setGeometry(QtCore.QRect(80, 60, 51, 21))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        self.label_AMin.setFont(font)
        self.label_AMin.setAlignment(QtCore.Qt.AlignCenter)
        self.label_AMin.setObjectName("label_AMin")
        self.label_BMin = QtWidgets.QLabel(self.widget_12)
        self.label_BMin.setGeometry(QtCore.QRect(80, 110, 51, 21))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        self.label_BMin.setFont(font)
        self.label_BMin.setAlignment(QtCore.Qt.AlignCenter)
        self.label_BMin.setObjectName("label_BMin")
        self.horizontalSlider_LMax = QtWidgets.QSlider(self.widget_12)
        self.horizontalSlider_LMax.setGeometry(QtCore.QRect(210, 35, 169, 22))
        self.horizontalSlider_LMax.setMaximum(255)
        self.horizontalSlider_LMax.setPageStep(1)
        self.horizontalSlider_LMax.setProperty("value", 255)
        self.horizontalSlider_LMax.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_LMax.setObjectName("horizontalSlider_LMax")
        self.horizontalSlider_AMax = QtWidgets.QSlider(self.widget_12)
        self.horizontalSlider_AMax.setGeometry(QtCore.QRect(210, 85, 169, 22))
        self.horizontalSlider_AMax.setMaximum(255)
        self.horizontalSlider_AMax.setPageStep(1)
        self.horizontalSlider_AMax.setProperty("value", 255)
        self.horizontalSlider_AMax.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_AMax.setObjectName("horizontalSlider_AMax")
        self.horizontalSlider_BMax = QtWidgets.QSlider(self.widget_12)
        self.horizontalSlider_BMax.setGeometry(QtCore.QRect(210, 135, 169, 22))
        self.horizontalSlider_BMax.setMaximum(255)
        self.horizontalSlider_BMax.setPageStep(1)
        self.horizontalSlider_BMax.setProperty("value", 255)
        self.horizontalSlider_BMax.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_BMax.setObjectName("horizontalSlider_BMax")
        self.label_LMax = QtWidgets.QLabel(self.widget_12)
        self.label_LMax.setGeometry(QtCore.QRect(270, 10, 51, 20))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        self.label_LMax.setFont(font)
        self.label_LMax.setAlignment(QtCore.Qt.AlignCenter)
        self.label_LMax.setObjectName("label_LMax")
        self.label_AMax = QtWidgets.QLabel(self.widget_12)
        self.label_AMax.setGeometry(QtCore.QRect(270, 60, 51, 20))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        self.label_AMax.setFont(font)
        self.label_AMax.setAlignment(QtCore.Qt.AlignCenter)
        self.label_AMax.setObjectName("label_AMax")
        self.label_BMax = QtWidgets.QLabel(self.widget_12)
        self.label_BMax.setGeometry(QtCore.QRect(270, 110, 51, 20))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        self.label_BMax.setFont(font)
        self.label_BMax.setAlignment(QtCore.Qt.AlignCenter)
        self.label_BMax.setObjectName("label_BMax")
        self.widget_15 = QtWidgets.QWidget(self.tab)
        self.widget_15.setGeometry(QtCore.QRect(740, 380, 85, 161))
        self.widget_15.setStyleSheet("#widget_15 {border:1px solid #242424;\n"
"border-color: rgb(200, 200, 200);}")
        self.widget_15.setObjectName("widget_15")
        self.comboBox_color = QtWidgets.QComboBox(self.widget_15)
        self.comboBox_color.setGeometry(QtCore.QRect(10, 10, 69, 22))
        self.comboBox_color.setObjectName("comboBox_color")
        self.pushButton_labWrite = QtWidgets.QPushButton(self.widget_15)
        self.pushButton_labWrite.setGeometry(QtCore.QRect(5, 120, 75, 31))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        self.pushButton_labWrite.setFont(font)
        self.pushButton_labWrite.setStyleSheet("QPushButton{background-color: rgb(255, 165, 0);}\n"
"QPushButton:hover{background-color:  rgb(255, 210, 0);}\n"
"QPushButton{border-radius:5px;}")
        self.pushButton_labWrite.setObjectName("pushButton_labWrite")
        self.pushButton_addcolor = QtWidgets.QPushButton(self.widget_15)
        self.pushButton_addcolor.setGeometry(QtCore.QRect(5, 40, 75, 31))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        self.pushButton_addcolor.setFont(font)
        self.pushButton_addcolor.setStyleSheet("QPushButton{background-color: rgb(255, 165, 0);}\n"
"QPushButton:hover{background-color:  rgb(255, 210, 0);}\n"
"QPushButton{border-radius:5px;}")
        self.pushButton_addcolor.setObjectName("pushButton_addcolor")
        self.pushButton_deletecolor = QtWidgets.QPushButton(self.widget_15)
        self.pushButton_deletecolor.setGeometry(QtCore.QRect(5, 80, 75, 31))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        self.pushButton_deletecolor.setFont(font)
        self.pushButton_deletecolor.setStyleSheet("QPushButton{background-color: rgb(255, 165, 0);}\n"
"QPushButton:hover{background-color:  rgb(255, 210, 0);}\n"
"QPushButton{border-radius:5px;}")
        self.pushButton_deletecolor.setObjectName("pushButton_deletecolor")
        self.pushButton_connect = QtWidgets.QPushButton(self.tab)
        self.pushButton_connect.setGeometry(QtCore.QRect(100, 410, 121, 31))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        self.pushButton_connect.setFont(font)
        self.pushButton_connect.setStyleSheet("QPushButton{background-color: rgb(255, 165, 0);}\n"
"QPushButton:hover{background-color:  rgb(255, 210, 0);}\n"
"QPushButton{border-radius:5px;}")
        self.pushButton_connect.setObjectName("pushButton_connect")
        self.label_process = QtWidgets.QLabel(self.tab)
        self.label_process.setGeometry(QtCore.QRect(120, 50, 400, 300))
        self.label_process.setText("")
        self.label_process.setObjectName("label_process")
        self.label_orign = QtWidgets.QLabel(self.tab)
        self.label_orign.setGeometry(QtCore.QRect(680, 50, 400, 300))
        self.label_orign.setText("")
        self.label_orign.setObjectName("label_orign")
        self.pushButton_disconnect = QtWidgets.QPushButton(self.tab)
        self.pushButton_disconnect.setGeometry(QtCore.QRect(100, 490, 121, 31))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        self.pushButton_disconnect.setFont(font)
        self.pushButton_disconnect.setStyleSheet("QPushButton{background-color: rgb(255, 165, 0);}\n"
"QPushButton:hover{background-color:  rgb(255, 210, 0);}\n"
"QPushButton{border-radius:5px;}")
        self.pushButton_disconnect.setObjectName("pushButton_disconnect")
        self.pushButton_quit2_2 = QtWidgets.QPushButton(self.tab)
        self.pushButton_quit2_2.setGeometry(QtCore.QRect(990, 480, 100, 50))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(16)
        self.pushButton_quit2_2.setFont(font)
        self.pushButton_quit2_2.setStyleSheet("QPushButton{background-color: rgb(255, 165, 0);}\n"
"QPushButton:hover{background-color:  rgb(255, 210, 0);}\n"
"QPushButton{border-radius:5px;}")
        self.pushButton_quit2_2.setObjectName("pushButton_quit2_2")
        self.widget_15.raise_()
        self.widget_12.raise_()
        self.label_8.raise_()
        self.pushButton_connect.raise_()
        self.label_process.raise_()
        self.label_orign.raise_()
        self.pushButton_disconnect.raise_()
        self.pushButton_quit2_2.raise_()
        self.tabWidget.addTab(self.tab, "")

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Arm 1.0"))
        self.label_action.setText(_translate("Form", "动作组："))
        self.Button_DelectSingle.setText(_translate("Form", "单个擦除"))
        self.Button_AllDelect.setText(_translate("Form", "全部擦除"))
        self.Button_RunAction.setText(_translate("Form", "动作组运行"))
        self.Button_StopAction.setText(_translate("Form", "停止"))
        self.Button_Quit.setText(_translate("Form", "退出"))
        self.Button_Reflash.setText(_translate("Form", "刷新"))
        self.checkBox.setText(_translate("Form", "循环"))
        self.Button_Run.setText(_translate("Form", "运行"))
        self.Button_ReadDeviation.setText(_translate("Form", "读取偏差"))
        self.Button_SaveDeviation.setText(_translate("Form", "保存偏差"))
        self.Button_ReSetServos.setText(_translate("Form", "复位舵机"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form", "编号"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Form", "时间"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Form", "ID:1"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Form", "ID:3"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("Form", "ID:4"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("Form", "ID:5"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("Form", "ID:6"))
        self.Button_OpenActionGroup.setText(_translate("Form", "打开动作文件"))
        self.Button_SaveActionGroup.setText(_translate("Form", "保存动作文件"))
        self.Button_TandemActionGroup.setText(_translate("Form", "串联动作文件"))
        self.label_time.setText(_translate("Form", "动作时间"))
        self.lineEdit_time.setText(_translate("Form", "1000"))
        self.Button_AddAction.setText(_translate("Form", "添加动作"))
        self.Button_DelectAction.setText(_translate("Form", "删除动作"))
        self.Button_UpdateAction.setText(_translate("Form", "更新动作"))
        self.Button_InsertAction.setText(_translate("Form", "插入动作"))
        self.Button_MoveUpAction.setText(_translate("Form", "上移动作"))
        self.Button_MoveDownAction.setText(_translate("Form", "下移动作"))
        self.label_time_2.setText(_translate("Form", "总时长"))
        self.label.setText(_translate("Form", "ms"))
        self.label_5.setText(_translate("Form", "s"))
        self.label_TotalTime.setText(_translate("Form", "0"))
        self.Button_DelectAllAction.setText(_translate("Form", "删除全部"))
        self.radioButton_zn.setText(_translate("Form", "中文"))
        self.radioButton_en.setText(_translate("Form", "English"))
        self.label_ID1.setText(_translate("Form", "ID:1"))
        self.lineEdit_1.setText(_translate("Form", "1500"))
        self.label_d1.setText(_translate("Form", "0"))
        self.label_2.setText(_translate("Form", "<html><head/><body><p align=\"center\">合</p><p align=\"justify\"><br/></p></body></html>"))
        self.label_3.setText(_translate("Form", "<html><head/><body><p align=\"center\">开</p></body></html>"))
        self.label_ID3.setText(_translate("Form", "ID:3"))
        self.lineEdit_3.setText(_translate("Form", "1500"))
        self.label_7.setText(_translate("Form", "<html><head/><body><p align=\"center\">上</p></body></html>"))
        self.label_d3.setText(_translate("Form", "0"))
        self.label_9.setText(_translate("Form", "<html><head/><body><p align=\"center\">下</p></body></html>"))
        self.label_ID4.setText(_translate("Form", "ID:4"))
        self.lineEdit_4.setText(_translate("Form", "1500"))
        self.label_10.setText(_translate("Form", "<html><head/><body><p align=\"center\">下</p></body></html>"))
        self.label_d4.setText(_translate("Form", "0"))
        self.label_12.setText(_translate("Form", "<html><head/><body><p align=\"center\">上</p></body></html>"))
        self.label_ID5.setText(_translate("Form", "ID:5"))
        self.lineEdit_5.setText(_translate("Form", "1500"))
        self.label_13.setText(_translate("Form", "<html><head/><body><p align=\"center\">下</p></body></html>"))
        self.label_d5.setText(_translate("Form", "0"))
        self.label_15.setText(_translate("Form", "<html><head/><body><p align=\"center\">上</p></body></html>"))
        self.label_ID6.setText(_translate("Form", "ID:6"))
        self.lineEdit_6.setText(_translate("Form", "1500"))
        self.label_16.setText(_translate("Form", "<html><head/><body><p align=\"center\">左</p></body></html>"))
        self.label_d6.setText(_translate("Form", "0"))
        self.label_18.setText(_translate("Form", "<html><head/><body><p align=\"center\">右</p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_1), _translate("Form", "普通模式"))
        self.label_8.setText(_translate("Form", "400x300原图"))
        self.label_25.setText(_translate("Form", "L"))
        self.label_26.setText(_translate("Form", "A"))
        self.label_27.setText(_translate("Form", "B"))
        self.label_LMin.setText(_translate("Form", "0"))
        self.label_AMin.setText(_translate("Form", "0"))
        self.label_BMin.setText(_translate("Form", "0"))
        self.label_LMax.setText(_translate("Form", "255"))
        self.label_AMax.setText(_translate("Form", "255"))
        self.label_BMax.setText(_translate("Form", "255"))
        self.pushButton_labWrite.setText(_translate("Form", "保存"))
        self.pushButton_addcolor.setText(_translate("Form", "新增"))
        self.pushButton_deletecolor.setText(_translate("Form", "删除"))
        self.pushButton_connect.setText(_translate("Form", "连接"))
        self.pushButton_disconnect.setText(_translate("Form", "断开"))
        self.pushButton_quit2_2.setText(_translate("Form", "退出"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Form", "摄像头工具"))

import resource_rc
